name: chat
description: chat app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_chat_ui: ^1.6.3
  file_picker: ^4.6.1
  flutter_chat_types: ^3.4.3
  http: ^0.13.4
  image_picker: ^0.8.5+3
  mime: ^1.0.2
  open_file: ^3.2.1
  path_provider: ^2.0.11
  uuid: ^3.0.6
  get: ^4.6.5
  record: ^4.3.1
  just_audio: ^0.9.28
  lottie: ^1.3.0

assets:
  - assets/

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
